# Generated by Django 3.2.6 on 2022-04-18 16:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='partner/images'), size=8)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('short_description', models.CharField(max_length=255)),
                ('creators', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='project/images'), size=8)),
            ],
        ),
    ]
