# Generated by Django 3.2.6 on 2022-04-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_partner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.CharField(blank=True, choices=[('EN', 'Английский'), ('RUS', 'Русский'), ('MATH', 'Математика'), ('PHYS', 'Физика'), ('SOC', 'Обществознание'), ('BIO', 'Биология'), ('LIT', 'Литература'), ('HIST', 'История'), ('INF', 'Информатика'), ('GEO', 'География')], max_length=20, null=True),
        ),
    ]
