# Generated by Django 3.2.6 on 2022-04-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_project_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerimage',
            name='partner',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='PartnerImage',
        ),
    ]
